// <auto-generated />
using System;
using Doctheca.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Doctheca.Database.Migrations
{
    [DbContext(typeof(DocthecaDbContext))]
    [Migration("20260930161548_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Doctheca.Database.Entities.DocumentFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("Grade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grade");

                    b.Property<Guid?>("StructaDocDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("structadoc_document_id");

                    b.Property<string>("Subject")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Year")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("FileName");

                    b.ToTable("document_files", t =>
                        {
                            t.HasTrigger("set_document_files_updated_at");
                        });
                });

            modelBuilder.Entity("Doctheca.Database.Entities.DocumentParseBlockEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float?>("BboxX0")
                        .HasColumnType("real")
                        .HasColumnName("bbox_x0");

                    b.Property<float?>("BboxX1")
                        .HasColumnType("real")
                        .HasColumnName("bbox_x1");

                    b.Property<float?>("BboxY0")
                        .HasColumnType("real")
                        .HasColumnName("bbox_y0");

                    b.Property<float?>("BboxY1")
                        .HasColumnType("real")
                        .HasColumnName("bbox_y1");

                    b.Property<string>("BlockData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("block_data");

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("block_type");

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<double?>("MineruScore")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<int>("PageId")
                        .HasColumnType("integer")
                        .HasColumnName("page_id");

                    b.Property<Guid>("ParseId")
                        .HasColumnType("uuid")
                        .HasColumnName("parse_id");

                    b.Property<int>("SortIndex")
                        .HasColumnType("integer")
                        .HasColumnName("sort_index");

                    b.Property<string>("SubType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sub_type");

                    b.Property<string>("TextContent")
                        .HasColumnType("text")
                        .HasColumnName("text_content");

                    b.Property<string>("TextFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("text_format");

                    b.Property<int>("TextLevel")
                        .HasColumnType("integer")
                        .HasColumnName("text_level");

                    b.HasKey("Id");

                    b.HasIndex("BlockType");

                    b.HasIndex("ImageId");

                    b.HasIndex("ParseId", "PageId", "SortIndex");

                    b.ToTable("document_parse_blocks");
                });

            modelBuilder.Entity("Doctheca.Database.Entities.DocumentParseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentList")
                        .HasColumnType("jsonb")
                        .HasColumnName("content_list");

                    b.Property<string>("ContentListV2")
                        .HasColumnType("jsonb")
                        .HasColumnName("content_list_v2");

                    b.Property<Guid>("DocumentFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_file_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ExternalTaskId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_task_id");

                    b.Property<string>("LayoutJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("layout_json");

                    b.Property<string>("MarkdownContent")
                        .HasColumnType("text")
                        .HasColumnName("markdown_content");

                    b.Property<string>("ModelJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("model_json");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("model_version");

                    b.Property<DateTimeOffset?>("ParsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("parsed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid?>("StructaDocParseRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("structadoc_parse_run_id");

                    b.Property<string>("ZipPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("zip_path");

                    b.HasKey("Id");

                    b.HasIndex("DocumentFileId");

                    b.HasIndex("ModelVersion");

                    b.HasIndex("Status");

                    b.ToTable("document_parses");
                });

            modelBuilder.Entity("Doctheca.Database.Entities.DocumentParseImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("content_type");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("image_name");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_path");

                    b.Property<Guid>("ParseId")
                        .HasColumnType("uuid")
                        .HasColumnName("parse_id");

                    b.HasKey("Id");

                    b.HasIndex("ParseId");

                    b.ToTable("document_parse_images");
                });

            modelBuilder.Entity("Doctheca.Database.Entities.DocumentParseBlockEntity", b =>
                {
                    b.HasOne("Doctheca.Database.Entities.DocumentParseImageEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Doctheca.Database.Entities.DocumentParseEntity", "Parse")
                        .WithMany()
                        .HasForeignKey("ParseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Parse");
                });

            modelBuilder.Entity("Doctheca.Database.Entities.DocumentParseEntity", b =>
                {
                    b.HasOne("Doctheca.Database.Entities.DocumentFileEntity", "DocumentFile")
                        .WithMany()
                        .HasForeignKey("DocumentFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentFile");
                });

            modelBuilder.Entity("Doctheca.Database.Entities.DocumentParseImageEntity", b =>
                {
                    b.HasOne("Doctheca.Database.Entities.DocumentParseEntity", "Parse")
                        .WithMany()
                        .HasForeignKey("ParseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parse");
                });
#pragma warning restore 612, 618
        }
    }
}
