/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDrawer: typeof import('./src/components/AppDrawer.vue')['default']
    AppModal: typeof import('./src/components/AppModal.vue')['default']
    AppToast: typeof import('./src/components/AppToast.vue')['default']
    ChartDonut: typeof import('./src/components/ChartDonut.vue')['default']
    ChartLine: typeof import('./src/components/ChartLine.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    StatusStrip: typeof import('./src/components/StatusStrip.vue')['default']
    Topbar: typeof import('./src/components/Topbar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
