using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Doctheca.Database;
using Npgsql;
using Xunit;

namespace Doctheca.Tests.Database;

// The same matrix is first run against the original executor, then against shared evidence.
// Each shape begins from a fresh real PostgreSQL baseline; no mocked schema facts.
[Collection(MigrationIntegrationCollection.Name)]
public sealed class SchemaEvidenceCompatibilityTests(PostgreSqlMigrationFixture fixture) : IAsyncLifetime
{
    private string _database = null!;
    public async Task InitializeAsync() => _database = await fixture.CreateDatabaseAsync();
    public Task DisposeAsync() => fixture.DropDatabaseAsync(_database);

    public static IEnumerable<object[]> Shapes()
    {
        var cases = new (string Name, string Sql, bool Reject, bool Backfill)[] {
            ("pk-name", "ALTER TABLE document_files RENAME CONSTRAINT \"PK_document_files\" TO renamed_pk", true, false),
            ("pk-case", "ALTER TABLE document_files RENAME CONSTRAINT \"PK_document_files\" TO pk_document_files", false, false),
            ("fk-name", "ALTER TABLE document_parses RENAME CONSTRAINT \"FK_document_parses_document_files_document_file_id\" TO renamed_fk", true, false),
            ("fk-case", "ALTER TABLE document_parses RENAME CONSTRAINT \"FK_document_parses_document_files_document_file_id\" TO fk_document_parses_document_files_document_file_id", false, false),
            ("fk-delete", "ALTER TABLE document_parses DROP CONSTRAINT \"FK_document_parses_document_files_document_file_id\"; ALTER TABLE document_parses ADD CONSTRAINT \"FK_document_parses_document_files_document_file_id\" FOREIGN KEY(document_file_id) REFERENCES document_files(id) ON DELETE RESTRICT", true, false),
            ("fk-extra", "ALTER TABLE document_parses ADD CONSTRAINT extra_fk FOREIGN KEY(document_file_id) REFERENCES document_files(id)", true, false),
            ("index-case", "ALTER INDEX \"IX_document_files_file_name\" RENAME TO ix_document_files_file_name", false, false),
            ("index-name", "ALTER INDEX \"IX_document_files_file_name\" RENAME TO renamed_index", false, true),
            ("index-missing", "DROP INDEX \"IX_document_files_file_name\"", false, true),
            ("index-order", "DROP INDEX \"IX_document_parse_blocks_parse_id_page_id_sort_index\"; CREATE INDEX \"IX_document_parse_blocks_parse_id_page_id_sort_index\" ON document_parse_blocks(page_id, parse_id, sort_index)", true, false),
            ("index-unique", "DROP INDEX \"IX_document_files_file_name\"; CREATE UNIQUE INDEX \"IX_document_files_file_name\" ON document_files(file_name)", true, false),
            ("index-expression", "DROP INDEX \"IX_document_files_file_name\"; CREATE INDEX \"IX_document_files_file_name\" ON document_files(lower(file_name))", true, false),
            ("index-include", "DROP INDEX \"IX_document_files_file_name\"; CREATE INDEX \"IX_document_files_file_name\" ON document_files(file_name) INCLUDE(id)", true, false),
            ("index-swapped-names", "ALTER INDEX \"IX_document_parses_model_version\" RENAME TO temporary_index; ALTER INDEX \"IX_document_parses_status\" RENAME TO \"IX_document_parses_model_version\"; ALTER INDEX temporary_index RENAME TO \"IX_document_parses_status\"", true, false),
            ("extra-same-index", "CREATE INDEX extra_same_shape ON document_files(file_name)", false, false),
            ("extra-expression", "CREATE INDEX extra_expression ON document_files(lower(file_name))", false, false),
            ("extra-include", "CREATE INDEX extra_include ON document_files(file_name) INCLUDE(id)", false, false),
            ("unrelated-duplicate", "CREATE TABLE unrelated(value text); CREATE INDEX unrelated_a ON unrelated(value); CREATE INDEX unrelated_b ON unrelated(value)", false, false),
            ("unrelated-duplicate-fk", "CREATE TABLE unrelated(id uuid REFERENCES document_files(id)); ALTER TABLE unrelated ADD FOREIGN KEY(id) REFERENCES document_files(id)", false, false),
            ("identity", "ALTER TABLE document_parse_blocks ALTER COLUMN sort_index ADD GENERATED BY DEFAULT AS IDENTITY", false, false),
            ("column-nullability", "ALTER TABLE document_files ALTER COLUMN file_name DROP NOT NULL", true, false),
            ("column-type", "ALTER TABLE document_files ALTER COLUMN file_name TYPE text", true, false),
            ("column-extra", "ALTER TABLE document_files ADD COLUMN extra_value text", true, false),
            ("missing-nullable", "ALTER TABLE document_files DROP COLUMN subject", false, true),
            ("missing-default", "ALTER TABLE document_files DROP COLUMN created_at", false, true),
            ("missing-required", "ALTER TABLE document_parses DROP COLUMN model_version CASCADE", true, false),
        };
        foreach (var current in new[] { false, true })
        foreach (var c in cases)
            yield return [c.Name, c.Sql, current, c.Reject || current && c.Backfill, c.Backfill];
    }

    [Theory]
    [MemberData(nameof(Shapes))]
    public async Task OriginalDecisionsRemainExact(string scenario, string sql, bool current, bool reject, bool backfill)
    {
        using var context = fixture.CreateContext(_database);
        var executor = new DocthecaMigrationExecutor(context, NullLogger.Instance);
        if (current) await executor.ExecuteAsync();
        else await MigrationGoldenStates.EnsureCreatedLegacyAsync(context);
        await MigrationGoldenStates.ExecuteRawAsync(context, sql);
        var beforeColumns = await MigrationGoldenStates.ReadColumnShapeAsync(context);
        var beforeConstraints = await MigrationGoldenStates.ReadConstraintShapeAsync(context);
        var inspection = await executor.InspectDetailedAsync(default);
        var expected = reject ? DocthecaMigrationExecutor.DatabaseState.InspectionFailed : current
            ? DocthecaMigrationExecutor.DatabaseState.CurrentVersionCompatible : DocthecaMigrationExecutor.DatabaseState.LegacyTakeoverRequired;
        Assert.True(inspection.State == expected, "Unexpected classification in shape " + scenario);
        Assert.Equal(beforeColumns, await MigrationGoldenStates.ReadColumnShapeAsync(context));
        Assert.Equal(beforeConstraints, await MigrationGoldenStates.ReadConstraintShapeAsync(context));
        if (reject)
        {
            var failure = await Assert.ThrowsAsync<InvalidOperationException>(() => executor.ExecuteAsync());
            Assert.Contains(DocthecaMigrationExecutor.IncompatibleErrorCode, failure.Message);
            Assert.Equal(beforeColumns, await MigrationGoldenStates.ReadColumnShapeAsync(context));
            Assert.Equal(beforeConstraints, await MigrationGoldenStates.ReadConstraintShapeAsync(context));
        }
        else
        {
            await executor.ExecuteAsync();
            Assert.Equal(DocthecaMigrationExecutor.DatabaseState.CurrentVersionCompatible, await executor.InspectAsync());
            Assert.Equal(new[] { MigrationGoldenStates.InitialId }, await MigrationGoldenStates.ReadAppliedHistoryAsync(context));
            if (!backfill) Assert.Equal(beforeColumns, await MigrationGoldenStates.ReadColumnShapeAsync(context));
        }
        // Inspect and refusal do not synthesize or mutate history.
        Assert.Equal(current || !reject, await MigrationGoldenStates.ScalarAsync<bool>(context, "SELECT to_regclass('public.\"__EFMigrationsHistory\"') IS NOT NULL"));
    }

    [Fact]
    public async Task UnknownHistoryPrecedesUnrepresentableUnrelatedShapes()
    {
        using var context = fixture.CreateContext(_database);
        var executor = new DocthecaMigrationExecutor(context, NullLogger.Instance);
        await executor.ExecuteAsync();
        await MigrationGoldenStates.ExecuteRawAsync(context, "INSERT INTO \"__EFMigrationsHistory\" VALUES ('future-version', '1'); CREATE TABLE unrelated(value text); CREATE INDEX a ON unrelated(value); CREATE INDEX b ON unrelated(value)");
        Assert.Equal(DocthecaMigrationExecutor.DatabaseState.VersionTooNew, await executor.InspectAsync());
        await Assert.ThrowsAsync<InvalidOperationException>(() => executor.ExecuteAsync());
        Assert.Equal(2, (await MigrationGoldenStates.ReadAppliedHistoryAsync(context)).Count);
    }

    [Fact]
    public async Task UnknownPublicHistoryPrecedesUnrepresentableMappedTable()
    {
        using var context = fixture.CreateContext(_database);
        var executor = new DocthecaMigrationExecutor(context, NullLogger.Instance);
        await executor.ExecuteAsync();
        await MigrationGoldenStates.ExecuteRawAsync(context,
            "INSERT INTO \"__EFMigrationsHistory\" VALUES ('future-version', '1'); " +
            "DROP TABLE document_parse_blocks; CREATE TABLE document_parse_blocks()");
        Assert.Equal(DocthecaMigrationExecutor.DatabaseState.VersionTooNew, await executor.InspectAsync());
        await Assert.ThrowsAsync<InvalidOperationException>(() => executor.ExecuteAsync());
        Assert.Equal(2, (await MigrationGoldenStates.ReadAppliedHistoryAsync(context)).Count);
    }

    [Fact]
    public async Task OtherSchemaHistoryDoesNotClaimPublicCurrentVersion()
    {
        using (var seed = fixture.CreateContext(_database))
        {
            await MigrationGoldenStates.EnsureCreatedLegacyAsync(seed);
            await MigrationGoldenStates.ExecuteRawAsync(seed, "CREATE SCHEMA alternate; CREATE TABLE alternate.\"__EFMigrationsHistory\" (\"MigrationId\" text, \"ProductVersion\" text); INSERT INTO alternate.\"__EFMigrationsHistory\" VALUES ('future-version', '1')");
        }
        var connection = new NpgsqlConnectionStringBuilder(fixture.GetConnectionString(_database)) { SearchPath = "alternate,public" };
        using var context = fixture.CreateContextWithConnectionString(connection.ConnectionString);
        Assert.Equal(DocthecaMigrationExecutor.DatabaseState.LegacyTakeoverRequired, await new DocthecaMigrationExecutor(context).InspectAsync());
    }
}
